/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.org.reprintframes;

import com.org.DB.ConnectionSet1;
import com.org.clz.tablemodel1;
import com.toedter.calendar.JDateChooser;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tuan
 */
public class reprint_printing extends javax.swing.JFrame {

    /**
     * Creates new form reprint_printing
     */
    SimpleDateFormat d1, d2;
    Timer t;

    public reprint_printing() {
        initComponents();

        dateMethod();
        tableLoad();
    }

    public static String datechosser(JDateChooser jd) {
        SimpleDateFormat sd = new SimpleDateFormat("dd /MMMM /yyyy");
        Date d = jd.getDate();
        String date = sd.format(d);
        System.out.println(date);
        return date;

    }

    void dateMethod() {
        //set date & time
        d1 = new SimpleDateFormat("yyyy/ MMM/ dd/ EEEE");
        d2 = new SimpleDateFormat("  hh:mm aaa");
        t = new Timer(100, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                date.setText(d1.format(d));
                time.setText(d2.format(d));


            }
        });
        t.start();
    }

    void tableLoad() {
        try {

            new tablemodel1().fillTable("select idreprint_stores,idjob_card,manuscript_name,fname,isbn,pduct_sz,nm_pages,reprint_qty from reprint_prntshedul sh1 inner join reprint_director d1 on sh1.reprint_stores_idreprint_stores=d1.reprint_stores_idreprint_stores inner join reprint_stores rs1 "
                    + "on d1.reprint_stores_idreprint_stores = rs1.idreprint_stores inner join job_card j1 on rs1.job_card_idjob_card = j1.idjob_card inner join production_description dis1 on j1.idjob_card = dis1.job_card_idjob_card inner join reseving_manuscript m1 on j1.reseving_manuscript_idrm = m1.idrm "
                    + "inner join author a1 on m1.author_idauthor = a1.idauthor where rp_status_print='No'", jTable1);

            new tablemodel1().fillTable("select idreprint_stores,idjob_card,manuscript_name,fname,isbn,rp_cver_print_dte,rp_qty,rp_insde_printed_dte,rp_paper_rim,rp_cmplt_date,re_printing_step from reprinting p1 "
                    + "inner join reprint_prntshedul ph1 on p1.reprint_prntshedul_idreprint_prntshedul = ph1.idreprint_prntshedul inner join reprint_stores rs1 on ph1.reprint_stores_idreprint_stores = rs1.idreprint_stores "
                    + "inner join job_card j1 on rs1.job_card_idjob_card = j1.idjob_card inner join reseving_manuscript m1 on j1.reseving_manuscript_idrm = m1.idrm inner join author a1 on m1.author_idauthor = a1.idauthor "
                    + "where rp_status_print='Yes'", jTable2);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(reprint_printing.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(reprint_printing.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(reprint_printing.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    void clear() {
        jLabel14.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField6.setText("");
        jTextField13.setText("");
        jTextField5.setText("");
        jTextField11.setText("");
        jTextField7.setText("");
        jTextField4.setText("");
        jTextField14.setText("");
        jLabel6.setText("");
        jLabel7.setText("");
        jTextField15.setText("");
        jTextField19.setText("");
        jDateChooser2.setDate(null);
        jDateChooser3.setDate(null);
        jTextField17.setText("");
        jTextField18.setText("");
        jDateChooser1.setDate(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel24 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField8 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField12 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("* Cover Printed Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 740, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("* Inside Printed Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 770, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("* Used Paper Reams");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 800, 150, -1));

        jTextField17.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField17KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 800, 200, -1));
        getContentPane().add(jDateChooser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 770, 200, -1));
        getContentPane().add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 740, 200, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("* Quantity");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 740, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("* Complete Date");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 770, -1, -1));

        jTextField18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField18KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 740, 200, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 770, 200, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Reprint");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 100, 58));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pub/img/sarasavi.png"))); // NOI18N
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 267, 70));

        date.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 230, 41));

        time.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 60, 140, 26));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Job Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Product Size");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jTextField6.setEditable(false);
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 290, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Number Of Pages");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, -1, -1));

        jTextField4.setEditable(false);
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 270, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Paper Type");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Innser Pages");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Cover");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Board Type");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Gauge");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Gauge");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Print Quantity");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, -1, -1));

        jTextField7.setEditable(false);
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, 270, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Book Title");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Author");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jTextField9.setEditable(false);
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 290, -1));

        jTextField10.setEditable(false);
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 290, -1));

        jTextField11.setEditable(false);
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 270, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("ISBN");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("ISBN");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        jLabel67.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel67.setText("Job No ");
        jPanel1.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, -1, -1));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 120, 80, 20));

        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 110, 40, 20));

        jTextField13.setEditable(false);
        jPanel1.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 270, -1));

        jTextField5.setEditable(false);
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 270, -1));

        jTextField14.setEditable(false);
        jPanel1.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 110, -1));

        jTextField15.setEditable(false);
        jPanel1.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 110, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Print Attemt");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 100, -1));

        jTextField19.setEditable(false);
        jPanel1.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 150, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 1070, 190));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New Jobs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reprint Id", "Job No", "Book Title", "Author ", "ISBN", "Product Size", "Number Of Pages", "Print Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel8.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 1090, 140));

        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField8KeyReleased(evt);
            }
        });
        jPanel8.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 295, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Search");
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 55, -1));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1130, 210));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Completed Jobs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reprint Id", "Job No", "Title", "Author", "ISBN", "Cover Prinyed Date", "Quantity", "Inside Printed Date", "Used Paper Rims", "Complete Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jPanel9.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 1050, 140));

        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField12KeyReleased(evt);
            }
        });
        jPanel9.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 295, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Search");
        jPanel9.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 55, -1));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 1090, 210));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Save");
        jButton6.setBorder(null);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 840, 108, 45));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("Delete");
        jButton7.setBorder(null);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 840, 108, 45));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("Update");
        jButton8.setBorder(null);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 840, 108, 45));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 100, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 843, 100, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField17KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField17KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (c != evt.VK_BACK_SPACE && c != evt.VK_DELETE) {

            if (!(c == '.' || c == '0' || c == '1' || c == '2' || c == '3' || c == '4' || c == '5' || c == '6' || c == '7' || c == '8' || c == '9')) {

                evt.consume();
            }
        }
    }//GEN-LAST:event_jTextField17KeyTyped

    private void jTextField18KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField18KeyTyped
        // TODO add your handling code here:
        //validate (only numbers)
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField18KeyTyped

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            // TODO add your handling code here:
            //        set data for the feilds
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            int i = jTable1.getSelectedRow();
            String reprintId = dtm.getValueAt(i, 0).toString();

            ResultSet rs = ConnectionSet1.getInstance().getResult("select idreprint_stores,idjob_card,manuscript_name,fname,isbn,pduct_sz,nm_pages,reprint_qty,paper_type,paper_gauge,bordr_typ,bordr_gauge,print_attempt,idreprint_prntshedul from reprint_prntshedul sh1 inner join reprint_director d1 on sh1.reprint_stores_idreprint_stores=d1.reprint_stores_idreprint_stores inner join reprint_stores rs1 "
                    + "on d1.reprint_stores_idreprint_stores = rs1.idreprint_stores inner join reprint_printingdep pd1 on rs1.idreprint_stores = pd1.reprint_stores_idreprint_stores inner join job_card j1 on rs1.job_card_idjob_card = j1.idjob_card inner join production_description dis1 on j1.idjob_card = dis1.job_card_idjob_card "
                    + "inner join reseving_manuscript m1 on j1.reseving_manuscript_idrm = m1.idrm inner join author a1 on m1.author_idauthor = a1.idauthor where rp_status_print='No'");

            if (rs.next()) {
                String shedulid = rs.getString("idreprint_prntshedul");
                jLabel7.setText(shedulid);

                String rpid = rs.getString("idreprint_stores");
                jLabel14.setText(rpid);

                String jobid = rs.getString("idjob_card");
                jLabel6.setText(jobid);

                String titel = rs.getString("manuscript_name");
                jTextField9.setText(titel);

                String author = rs.getString("fname");
                jTextField10.setText(author);

                String isbn = rs.getString("isbn");
                jTextField11.setText(isbn);

                String psiz = rs.getString("pduct_sz");
                jTextField6.setText(psiz);

                String nop = rs.getString("nm_pages");
                jTextField4.setText(nop);

                String qty = rs.getString("reprint_qty");
                jTextField7.setText(qty);

                String ptyp = rs.getString("paper_type");
                jTextField13.setText(ptyp);

                String pgage = rs.getString("paper_gauge");
                jTextField14.setText(pgage);

                String btyp = rs.getString("bordr_typ");
                jTextField5.setText(btyp);

                String bgage = rs.getString("bordr_gauge");
                jTextField15.setText(bgage);

                String patmt = rs.getString("print_attempt");
                jTextField19.setText(patmt);

            }

        } catch (Exception ex) {
            Logger.getLogger(reprint_printing.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        all the data clear
        clear();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (jLabel6.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Select The Reprint Details In The Table", "error", JOptionPane.WARNING_MESSAGE);
        }else if(jTextField18.getText().isEmpty() || datechosser(jDateChooser1).isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Select The Date", "Error", JOptionPane.WARNING_MESSAGE);
            
        } else {
            try {
                // TODO add your handling code here:
                //        save the data
                String cverp = datechosser(jDateChooser2);
                String insidp = datechosser(jDateChooser3);
                String perrim = jTextField17.getText();
                String qty = jTextField18.getText();
                String cmplt = datechosser(jDateChooser1);
                String atmpt = jTextField19.getText();

                int repntshdulid = 0;
                ResultSet rs = ConnectionSet1.getInstance().getResult("select idreprint_prntshedul from reprint_prntshedul where idreprint_prntshedul='" + jLabel7.getText() + "'");
                if (rs.next()) {
                    repntshdulid = rs.getInt("idreprint_prntshedul");
                }

                System.out.println(repntshdulid);

                ConnectionSet1.getInstance().setResult("insert into reprinting(rp_cver_print_dte,rp_insde_printed_dte,rp_paper_rim,rp_qty,rp_cmplt_date,reprint_prntshedul_idreprint_prntshedul,re_printing_step) "
                        + "values('" + cverp + "','" + insidp + "','" + perrim + "','" + qty + "','" + cmplt + "','" + repntshdulid + "','" + atmpt + "')");

                ConnectionSet1.getInstance().setResult("update reprint_prntshedul set rp_status_print='Yes' where idreprint_prntshedul='" + repntshdulid + "'");


            ConnectionSet1.getInstance().setResult("update reprint_publishing set pub_status='Finished' where reprint_stores_idreprint_stores='"+jLabel14.getText()+"'");
            ConnectionSet1.getInstance().setResult("update reprint_director set dir_status='Finished' where reprint_stores_idreprint_stores='"+jLabel14.getText()+"'");
            ConnectionSet1.getInstance().setResult("update reprint_printingdep set status_prnt='Finished' where reprint_stores_idreprint_stores='"+jLabel14.getText()+"'");
            ConnectionSet1.getInstance().setResult("update reprint_stores set reprntaply='Finished' where idreprint_stores='"+jLabel14.getText()+"'"); 

                clear();
                tableLoad();

            } catch (Exception ex) {
                Logger.getLogger(reprint_printing.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        try {
            // TODO add your handling code here:
            //        set data to the feilds
            DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
            int i = jTable2.getSelectedRow();
            String reprntId = dtm.getValueAt(i, 0).toString();

            ResultSet rs = ConnectionSet1.getInstance().getResult("select idreprint_stores,idjob_card,manuscript_name,fname,isbn,rp_cver_print_dte,rp_qty,rp_insde_printed_dte,rp_paper_rim,rp_cmplt_date,re_printing_step,pduct_sz,nm_pages,paper_type,paper_gauge,bordr_typ,bordr_gauge,print_attempt,idreprint_prntshedul,reprint_qty from reprinting rp1 "
                    + "inner join reprint_prntshedul sh1 on rp1.reprint_prntshedul_idreprint_prntshedul = sh1.idreprint_prntshedul inner join reprint_stores rs1 on sh1.reprint_stores_idreprint_stores = rs1.idreprint_stores inner join reprint_printingdep pri1 on rs1.idreprint_stores = pri1.reprint_stores_idreprint_stores inner join reprint_director pd1 on "
                    + "pri1.reprint_stores_idreprint_stores = pd1.reprint_stores_idreprint_stores inner join job_card j1 on rs1.job_card_idjob_card = j1.idjob_card inner join production_description p1 on j1.idjob_card = p1.job_card_idjob_card inner join reseving_manuscript m1 on j1.reseving_manuscript_idrm = m1.idrm inner join author a1 on m1.author_idauthor = a1.idauthor "
                    + "where rp_status_print='Yes'");

            if (rs.next()) {
                String shedulid = rs.getString("idreprint_prntshedul");
                jLabel7.setText(shedulid);

                String rpid = rs.getString("idreprint_stores");
                jLabel14.setText(rpid);

                String jobid = rs.getString("idjob_card");
                jLabel6.setText(jobid);

                String titel = rs.getString("manuscript_name");
                jTextField9.setText(titel);

                String author = rs.getString("fname");
                jTextField10.setText(author);

                String isbn = rs.getString("isbn");
                jTextField11.setText(isbn);

                String psiz = rs.getString("pduct_sz");
                jTextField6.setText(psiz);

                String nop = rs.getString("nm_pages");
                jTextField4.setText(nop);

                String qty = rs.getString("reprint_qty");
                jTextField7.setText(qty);

                String ptyp = rs.getString("paper_type");
                jTextField13.setText(ptyp);

                String pgage = rs.getString("paper_gauge");
                jTextField14.setText(pgage);

                String btyp = rs.getString("bordr_typ");
                jTextField5.setText(btyp);

                String bgage = rs.getString("bordr_gauge");
                jTextField15.setText(bgage);

                String patmt = rs.getString("print_attempt");
                jTextField19.setText(patmt);

                String cvrpdte = rs.getString("rp_cver_print_dte");
                Date d1 = new Date();
                d1.getDate();
                jDateChooser2.setDate(d1);

                String isidprnt = rs.getString("rp_insde_printed_dte");
                Date d2 = new Date();
                d2.getDate();
                jDateChooser3.setDate(d2);

                String paperrm = rs.getString("rp_paper_rim");
                jTextField17.setText(paperrm);

                String pntqty = rs.getString("rp_qty");
                jTextField18.setText(pntqty);

                String cmplt = rs.getString("rp_cmplt_date");
                Date d3 = new Date();
                d3.getDate();
                jDateChooser1.setDate(d3);

            }

        } catch (Exception ex) {
            Logger.getLogger(reprint_printing.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            // TODO add your handling code here:
            //        update the details
            String cverp = datechosser(jDateChooser2);
            String insidp = datechosser(jDateChooser3);
            String perrim = jTextField17.getText();
            String qty = jTextField18.getText();
            String cmplt = datechosser(jDateChooser1);
            //        String atmpt = jTextField19.getText();

            ConnectionSet1.getInstance().setResult("update reprinting set rp_cver_print_dte='" + cverp + "',rp_insde_printed_dte='" + insidp + "',rp_paper_rim='" + perrim + "',rp_qty='" + qty + "',rp_cmplt_date='" + cmplt + "' where reprint_prntshedul_idreprint_prntshedul='" + jLabel7.getText() + "'");

            clear();
            tableLoad();

        } catch (Exception ex) {
            Logger.getLogger(reprint_printing.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased
        try {
            // TODO add your handling code here:
            //        serch the data
            new tablemodel1().fillTable("select idreprint_stores,idjob_card,manuscript_name,fname,isbn,pduct_sz,nm_pages,reprint_qty from reprint_prntshedul sh1 inner join reprint_director d1 on sh1.reprint_stores_idreprint_stores=d1.reprint_stores_idreprint_stores inner join reprint_stores rs1 "
                    + "on d1.reprint_stores_idreprint_stores = rs1.idreprint_stores inner join job_card j1 on rs1.job_card_idjob_card = j1.idjob_card inner join production_description dis1 on j1.idjob_card = dis1.job_card_idjob_card inner join reseving_manuscript m1 on j1.reseving_manuscript_idrm = m1.idrm "
                    + "inner join author a1 on m1.author_idauthor = a1.idauthor where rp_status_print='No' AND (fname like('" + jTextField8.getText() + "%%" + "') or manuscript_name like('" + jTextField8.getText() + "%%%" + "'))", jTable1);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(reprint_printing.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(reprint_printing.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(reprint_printing.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jTextField8KeyReleased

    private void jTextField12KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyReleased
        try {
            // TODO add your handling code here:
            //        search the data
            new tablemodel1().fillTable("select idreprint_stores,idjob_card,manuscript_name,fname,isbn,rp_cver_print_dte,rp_qty,rp_insde_printed_dte,rp_paper_rim,rp_cmplt_date,re_printing_step from reprinting p1 "
                    + "inner join reprint_prntshedul ph1 on p1.reprint_prntshedul_idreprint_prntshedul = ph1.idreprint_prntshedul inner join reprint_stores rs1 on ph1.reprint_stores_idreprint_stores = rs1.idreprint_stores "
                    + "inner join job_card j1 on rs1.job_card_idjob_card = j1.idjob_card inner join reseving_manuscript m1 on j1.reseving_manuscript_idrm = m1.idrm inner join author a1 on m1.author_idauthor = a1.idauthor "
                    + "where rp_status_print='Yes' AND (fname like('" + jTextField12.getText() + "%%" + "') or manuscript_name like('" + jTextField12.getText() + "%%%" + "'))", jTable2);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(reprint_printing.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(reprint_printing.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(reprint_printing.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jTextField12KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reprint_printing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reprint_printing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reprint_printing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reprint_printing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reprint_printing().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
