
import com.org.DB.ConnectionSet1;
import com.org.clz.tablemodel1;
import com.toedter.calendar.JDateChooser;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author tuan
 */
public class fullEvoluationProcess extends javax.swing.JFrame {

    /**
     * Creates new form fullEvoluationProcess
     */
    SimpleDateFormat d1, d2;
    Timer t;

    public fullEvoluationProcess() {
        initComponents();
        //
        jPanel10.setVisible(false);
        //
        dateMethod();

    }

    fullEvoluationProcess(String uname) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        this();
        jLabel61.setText(uname);
        tableLoad();

    }

    void tableLoad() {
        try {
            new tablemodel1().fillTable("select idrm,fname,contact_no,address,email,manuscript_name,catergory,ms_type from reseving_manuscript r1 inner join author t2 on r1.author_idauthor = t2.idauthor ORDER BY idrm DESC", jTable2);
            new tablemodel1().fillTable("select idrm,fname,contact_no,email,manuscript_name,catergory,ms_type,send_to,sent_by,sent_date from evaluation e1 inner join reseving_manuscript r1 on e1.reseving_manuscript_idrm = r1.idrm inner join author a1 on r1.author_idauthor = a1.idauthor", jTable3);
            new tablemodel1().fillTable("select idrm,fname,contact_no,email,manuscript_name,catergory,ms_type,send_to,sent_by,sent_date,decision from evaluation e1 inner join reseving_manuscript r1 on e1.reseving_manuscript_idrm = r1.idrm inner join author a1 on r1.author_idauthor = a1.idauthor where decision='Pending'", jTable4);
            new tablemodel1().fillTable("select idrm,fname,contact_no,email,manuscript_name,catergory,ms_type,send_to,sent_by,sent_date,recive_date,decision from evaluation e1 inner join reseving_manuscript r1 on e1.reseving_manuscript_idrm = r1.idrm inner join author a1 on r1.author_idauthor = a1.idauthor where decision='Approve'", jTable5);

            new tablemodel1().fillTable("select idrm,fname,contact_no,email,manuscript_name,catergory,ms_type,send_to,sent_by,sent_date,recive_date,decision from evaluation e1 inner join reseving_manuscript r1 on e1.reseving_manuscript_idrm = r1.idrm inner join author a1 on r1.author_idauthor = a1.idauthor where decision='Approve'", jTable6);
            new tablemodel1().fillTable("select idrm,fname,contact_no,email,manuscript_name,catergory,ms_type,send_to,sent_by,sent_date,recive_date,decision from evaluation e1 inner join reseving_manuscript r1 on e1.reseving_manuscript_idrm = r1.idrm inner join author a1 on r1.author_idauthor = a1.idauthor where decision='Reject'", jTable7);


        } catch (ClassNotFoundException ex) {
            Logger.getLogger(resivinManuScript.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(resivinManuScript.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(resivinManuScript.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public static String datechosser(JDateChooser jd) {
        SimpleDateFormat sd = new SimpleDateFormat("dd /MMMM /yyyy");
        Date d = jd.getDate();
        String date = sd.format(d);
        System.out.println(date);
        return date;

    }

    void dateMethod() {
        //set date & time
        d1 = new SimpleDateFormat("yyyy/ MMM/ dd/ EEEE");
        d2 = new SimpleDateFormat("  hh:mm aaa");
        t = new Timer(100, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                jLabel14.setText(d1.format(d));
                jLabel30.setText(d2.format(d));

                jLabel18.setText(d1.format(d));
                jLabel31.setText(d2.format(d));

                jLabel41.setText(d1.format(d));
                jLabel42.setText(d2.format(d));
            }
        });
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jButton11 = new javax.swing.JButton();
        jLabel61 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jTextField8 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel11 = new javax.swing.JPanel();
        jTextField14 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jTextField15 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        jTextField16 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jPanel14 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jComboBox7 = new javax.swing.JComboBox();
        jLabel50 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox();
        jLabel53 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jDateChooser5 = new com.toedter.calendar.JDateChooser();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Evaluvation Process");

        jTabbedPane5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Evaluvation Of The Manuscript");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 380, 58));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Date ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 210, 52));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 50, 110, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Search");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, 55, -1));

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 295, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New Manuscripts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Recive No", "Authour Name", "Contact No", "Address", "Email", "Script Name", "Catergory", "Script Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable2);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1130, 150));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1150, 190));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Manuscript Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Authour Name");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 31, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Contact Number");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 62, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Email");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 93, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Name Of The Manuscript");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Subject (Catergory)");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, -1, -1));

        jTextField1.setEditable(false);
        jPanel5.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 31, 291, -1));

        jTextField2.setEditable(false);
        jPanel5.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 62, 200, -1));

        jTextField3.setEditable(false);
        jPanel5.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 93, 270, -1));

        jTextField4.setEditable(false);
        jPanel5.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, 360, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel5.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 206, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Manuscript Type");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        jTextField6.setEditable(false);
        jPanel5.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 170, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Received No ");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, -1, -1));
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 30, 60, 20));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 1090, 150));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("* Sent To");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 70, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 170, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("* Sent By");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 70, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, 170, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("* Sent Date");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, 90, -1));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "All Sent Manuscripts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField7KeyReleased(evt);
            }
        });
        jPanel6.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 295, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Search");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 55, -1));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Recive No", "Authour Name", "Contact No", "Email", "Script Name", "Catergory", "Script Type", "Sent To", "Sent By", "Sent Date"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable3);

        jPanel6.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 1070, 160));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 1110, 240));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Save");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 490, 108, 45));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Update");
        jButton3.setBorder(null);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 810, 108, 45));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Clear");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 810, 108, 45));
        jPanel1.add(jDateChooser4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 490, 200, -1));

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton11.setText("Delete");
        jButton11.setBorder(null);
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 810, 108, 45));

        jLabel61.setText("jLabel61");
        jPanel1.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 40, 0));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pub/img/home.png"))); // NOI18N
        jButton12.setContentAreaFilled(false);
        jButton12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pub/img/home1.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 70));

        jTabbedPane5.addTab("Evaluvation Of The Manuscript", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 210, 52));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 50, 110, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Date ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setText("Approval of the Manuscript");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 10, 350, 58));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "All Sent Manuscripts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField8KeyReleased(evt);
            }
        });
        jPanel7.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 295, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Search");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 55, -1));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Recive No", "Authour Name", "Contact No", "Email", "Script Name", "Catergory", "Script Type", "Sent To", "Sent By", "Sent Date", "Decision"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTable4);

        jPanel7.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 1070, 110));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1110, 180));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Manuscript Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Authour Name");
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 31, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Contact Number");
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 62, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Email Address ");
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 93, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Name Of The Manuscript");
        jPanel8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Subject (Catergory)");
        jPanel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, -1, -1));

        jTextField9.setEditable(false);
        jPanel8.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 31, 291, -1));

        jTextField10.setEditable(false);
        jPanel8.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 62, 200, -1));

        jTextField11.setEditable(false);
        jPanel8.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 93, 270, -1));

        jTextField12.setEditable(false);
        jPanel8.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, 360, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel8.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 206, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Manuscript Type");
        jPanel8.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        jTextField13.setEditable(false);
        jPanel8.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 100, -1));
        jPanel8.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 20, 80, 30));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("Sent To");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 70, -1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel8.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 170, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("Sent By");
        jPanel8.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 70, -1));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel8.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 170, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setText("Sent Date");
        jPanel8.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 130, 90, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setText("Received No ");
        jPanel8.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, -1, -1));
        jPanel8.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 130, 150, 30));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 1090, 180));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Readers Opinian", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel35.setText("* Readers ");
        jPanel9.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));

        buttonGroup1.add(jCheckBox3);
        jCheckBox3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox3.setText("Approve");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel9.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        buttonGroup1.add(jCheckBox4);
        jCheckBox4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox4.setText("Reject");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanel9.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 100, -1));

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Why Reject", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel10.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 450, 80));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setText("Reason");
        jPanel10.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, -1));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 600, 110));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setText("* Recieved Date");
        jPanel9.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 110, -1));
        jPanel9.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 170, -1));

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 1070, 150));

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "All Resived Manuscripts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField14KeyReleased(evt);
            }
        });
        jPanel11.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 295, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setText("Search");
        jPanel11.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 55, -1));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Recive No", "Authour Name", "Contact No", "Email", "Script Name", "Catergory", "Script Type", "Sent To", "Sent By", "Sent Date", "Recieved Date", "Decision"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable5MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jTable5);

        jPanel11.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 1070, 130));

        jPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 1110, 200));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Save");
        jButton4.setBorder(null);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 820, 108, 45));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Update");
        jButton5.setBorder(null);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 820, 108, 45));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Clear");
        jButton6.setBorder(null);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 820, 108, 45));

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setText("Delete");
        jButton10.setBorder(null);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 820, 108, 45));

        jTabbedPane5.addTab("Approval of the Manuscript", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel39.setText("Approved/Rejected Manuscript");
        jPanel3.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 10, 380, 58));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel40.setText("Date ");
        jPanel3.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 30, -1, -1));

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 210, 52));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel3.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 50, 110, 30));

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "All Received Approved Manuscripts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField15KeyReleased(evt);
            }
        });
        jPanel12.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 295, -1));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel43.setText("Search");
        jPanel12.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 55, -1));

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Recive No", "Authour Name", "Contact No", "Email", "Script Name", "Catergory", "Script Type", "Sent To", "Sent By", "Sent Date", "Recieved Date", "Decision"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable6MouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(jTable6);

        jPanel12.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1090, 130));

        jPanel3.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1110, 200));

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "All Received Rijected Manuscripts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField16KeyReleased(evt);
            }
        });
        jPanel13.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 295, -1));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel44.setText("Search");
        jPanel13.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 55, -1));

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Recive No", "Authour Name", "Contact No", "Email", "Script Name", "Catergory", "Script Type", "Sent To", "Sent By", "Sent Date", "Recieved Date", "Decision"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable7MouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(jTable7);

        jPanel13.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1090, 140));

        jPanel3.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 1110, 220));

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Manuscript Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel45.setText("Authour Name");
        jPanel14.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 31, -1, -1));

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel46.setText("Contact Number");
        jPanel14.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 62, -1, -1));

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel47.setText("Email");
        jPanel14.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 93, -1, -1));

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel48.setText("Name Of The Manuscript");
        jPanel14.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, -1));

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel49.setText("Subject (Catergory)");
        jPanel14.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, -1, -1));

        jTextField17.setEditable(false);
        jPanel14.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 31, 291, -1));

        jTextField18.setEditable(false);
        jPanel14.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 62, 200, -1));

        jTextField19.setEditable(false);
        jPanel14.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 93, 270, -1));

        jTextField20.setEditable(false);
        jPanel14.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, 360, -1));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel14.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 206, -1));

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel50.setText("Manuscript Type");
        jPanel14.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        jTextField21.setEditable(false);
        jPanel14.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 100, -1));
        jPanel14.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 20, 80, 30));

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel52.setText("Sent To");
        jPanel14.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 70, -1));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel14.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 170, -1));

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel53.setText("Sent By");
        jPanel14.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 70, -1));

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel14.add(jComboBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 170, -1));

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel54.setText("Sent Date");
        jPanel14.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 130, 90, -1));

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel55.setText("Received No ");
        jPanel14.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, -1, -1));
        jPanel14.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 120, 140, 40));

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel57.setText("Recieved Date");
        jPanel14.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 110, -1));

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel58.setText("* Affter The Reconsideration of Manuscript ");
        jPanel14.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, 30));

        jCheckBox5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox5.setText("  Approve The Manuscript");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        jPanel14.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 220, -1));
        jPanel14.add(jDateChooser5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 200, -1));

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel59.setText("Decision");
        jPanel14.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 90, -1));
        jPanel14.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 140, 40));

        jPanel3.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 1090, 260));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("Clear");
        jButton7.setBorder(null);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 810, 108, 45));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("Delete");
        jButton8.setBorder(null);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 810, 108, 45));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setText("Update");
        jButton9.setBorder(null);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 810, 108, 45));

        jTabbedPane5.addTab("Approved / Rejected Manuscript", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
        // aprove or reject manuscript
        if (jCheckBox3.isSelected()) {
            jPanel10.setVisible(false);
        } else {
            jPanel10.setVisible(true);
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
        // aprove or reject manuscript
        if (jCheckBox4.isSelected()) {
            jPanel10.setVisible(true);
        } else {
            jPanel10.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
        // aprove or reject manuscript
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
        try {
            // TODO add your handling code here:
            // serch bar new manuscript
            tablemodel1.fillTable("select idrm,fname,contact_no,address,email,manuscript_name,catergory,ms_type from reseving_manuscript r1 inner join author t2 on r1.author_idauthor = t2.idauthor where fname like('" + jTextField5.getText() + "%%" + "') or manuscript_name like('" + jTextField5.getText() + "%%%" + "')", jTable2);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(fullEvoluationProcess.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(fullEvoluationProcess.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(fullEvoluationProcess.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jTextField5KeyReleased

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        //set value from the felds
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        int i = jTable2.getSelectedRow();
        Vector v = new Vector();
        String s = dtm.getValueAt(i, 0).toString();
        String s1 = dtm.getValueAt(i, 1).toString();
        String s2 = dtm.getValueAt(i, 2).toString();
        String s3 = dtm.getValueAt(i, 3).toString();
        String s4 = dtm.getValueAt(i, 4).toString();
        String s5 = dtm.getValueAt(i, 5).toString();
        String s6 = dtm.getValueAt(i, 6).toString();
        String s7 = dtm.getValueAt(i, 7).toString();

        jLabel3.setText(s);
        jTextField1.setText(s1);
        jTextField2.setText(s2);
        //s3 address
        jTextField3.setText(s4);
        jTextField4.setText(s5);

        v.add(s6);
        jComboBox1.setModel(new DefaultComboBoxModel(v));

        jTextField6.setText(s7);
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jLabel3.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Select The Manuscript", "error", JOptionPane.WARNING_MESSAGE);

        } else if (!jLabel3.getText().isEmpty()) {
            try {

                ResultSet rs1 = ConnectionSet1.getInstance().getResult("select reseving_manuscript_idrm from evaluation where reseving_manuscript_idrm='" + jLabel3.getText() + "'");
                if (rs1.next()) {
                    JOptionPane.showMessageDialog(this, "This Manuscript is Allready Assinged", "error", JOptionPane.WARNING_MESSAGE);
                    
                } else {
                    try {
                        // TODO add your handling code here:
                        // Save the evaluation process

                        int manu_script = 0;
                        ResultSet rs = ConnectionSet1.getInstance().getResult("select idrm from reseving_manuscript where idrm='" + jLabel3.getText() + "'");
                        if (rs.next()) {
                            manu_script = rs.getInt("idrm");
                        }

                        String sntto = jComboBox3.getSelectedItem().toString();
                        String sntby = jComboBox4.getSelectedItem().toString();
                        String sntdat = datechosser(jDateChooser4);
                        ConnectionSet1.getInstance().setResult("insert into evaluation(send_to, sent_by, sent_date,reseving_manuscript_idrm,decision) values('" + sntto + "','" + sntby + "','" + sntdat + "','" + manu_script + "','Pending')");

                        jLabel3.setText("");
                        jTextField1.setText("");
                        jTextField2.setText("");
                        jTextField3.setText("");
                        jTextField4.setText("");
                        jTextField6.setText("");
                        jComboBox1.setSelectedIndex(0);
                        jComboBox3.setSelectedIndex(0);
                        jComboBox4.setSelectedIndex(0);
                        jDateChooser4.setDate(null);
                        tableLoad();
                    } catch (Exception ex) {
                        Logger.getLogger(fullEvoluationProcess.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            } catch (Exception ex) {
                Logger.getLogger(fullEvoluationProcess.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
        // set data to update
        DefaultTableModel dtm = (DefaultTableModel) jTable3.getModel();
        int i = jTable3.getSelectedRow();
        Vector v = new Vector();
        Vector v1 = new Vector();
        Vector v2 = new Vector();
        String s = dtm.getValueAt(i, 0).toString();
        String s1 = dtm.getValueAt(i, 1).toString();
        String s2 = dtm.getValueAt(i, 2).toString();
        String s3 = dtm.getValueAt(i, 3).toString();
        String s4 = dtm.getValueAt(i, 4).toString();
        String s5 = dtm.getValueAt(i, 5).toString();
        String s6 = dtm.getValueAt(i, 6).toString();
        String s7 = dtm.getValueAt(i, 7).toString();
        String s8 = dtm.getValueAt(i, 8).toString();
        String s9 = dtm.getValueAt(i, 9).toString();

        jLabel3.setText(s);
        jTextField1.setText(s1);
        jTextField2.setText(s2);
        jTextField3.setText(s3);
        jTextField4.setText(s4);

        v.add(s5);
        jComboBox1.setModel(new DefaultComboBoxModel(v));

        jTextField6.setText(s6);

        v1.add(s7);
        jComboBox3.setModel(new DefaultComboBoxModel(v1));

        v2.add(s8);
        jComboBox4.setModel(new DefaultComboBoxModel(v2));

        Date d1 = new Date(s9);
        d1.getDate();
        jDateChooser4.setDate(d1);


    }//GEN-LAST:event_jTable3MouseClicked

    private void jTextField7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyReleased
        try {
            // TODO add your handling code here:
            // serch data
            new tablemodel1().fillTable("select idrm,fname,contact_no,email,manuscript_name,catergory,ms_type,send_to,sent_by,sent_date from evaluation e1 inner join reseving_manuscript r1 on e1.reseving_manuscript_idrm = r1.idrm inner join author a1 on r1.author_idauthor = a1.idauthor where fname like('" + jTextField7.getText() + "%%" + "') or manuscript_name like('" + jTextField7.getText() + "%%%" + "')", jTable3);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(fullEvoluationProcess.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(fullEvoluationProcess.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(fullEvoluationProcess.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jTextField7KeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (jLabel3.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Select The Manuscript", "error", JOptionPane.WARNING_MESSAGE);

        } else if (!jLabel3.getText().isEmpty()) {
            try {
                ResultSet rs1 = ConnectionSet1.getInstance().getResult("select reseving_manuscript_idrm from evaluation where reseving_manuscript_idrm='" + jLabel3.getText() + "'");
                if (rs1.next()) {
                    JOptionPane.showMessageDialog(this, "This Manuscript is Allready Assingrd", "error", JOptionPane.WARNING_MESSAGE);

                } else {
                    try {
                        // TODO add your handling code here:
                        // update the all manuscript table data
                        DefaultTableModel dtm = (DefaultTableModel) jTable3.getModel();

                        String sntto = jComboBox3.getSelectedItem().toString();
                        String sntby = jComboBox4.getSelectedItem().toString();
                        String sntdat = datechosser(jDateChooser4);

                        ConnectionSet1.getInstance().setResult("Update evaluation set send_to='" + sntto + "',sent_by='" + sntby + "',sent_date='" + sntdat + "' where reseving_manuscript_idrm='" + jLabel3.getText() + "'");
                        jLabel3.setText("");
                        jTextField1.setText("");
                        jTextField2.setText("");
                        jTextField3.setText("");
                        jTextField4.setText("");
                        jTextField6.setText("");
                        jComboBox1.setSelectedIndex(0);
                        jComboBox3.setSelectedIndex(0);
                        jComboBox4.setSelectedIndex(0);
                        jDateChooser4.setDate(null);
                        tableLoad();
                    } catch (Exception ex) {
                        Logger.getLogger(fullEvoluationProcess.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            } catch (Exception ex) {
                Logger.getLogger(fullEvoluationProcess.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased

        try {
            // TODO add your handling code here:
            // serch data
            new tablemodel1().fillTable("select idrm,fname,contact_no,email,manuscript_name,catergory,ms_type,send_to,sent_by,sent_date,decision from evaluation e1 inner join reseving_manuscript r1 on e1.reseving_manuscript_idrm = r1.idrm inner join author a1 on r1.author_idauthor = a1.idauthor where decision='Pending' and (fname like('" + jTextField8.getText() + "%%" + "') or manuscript_name like('" + jTextField8.getText() + "%%%" + "') or decision like('" + jTextField8.getText() + "%%%" + "'))", jTable4);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(fullEvoluationProcess.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(fullEvoluationProcess.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(fullEvoluationProcess.class.getName()).log(Level.SEVERE, null, ex);
        }



    }//GEN-LAST:event_jTextField8KeyReleased

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        // TODO add your handling code here:
        // set value from the all sent manu script table
        DefaultTableModel dtm = (DefaultTableModel) jTable4.getModel();
        int i = jTable4.getSelectedRow();
        Vector v = new Vector();
        Vector v1 = new Vector();
        Vector v2 = new Vector();
        String s = dtm.getValueAt(i, 0).toString();
        String s1 = dtm.getValueAt(i, 1).toString();
        String s2 = dtm.getValueAt(i, 2).toString();
        String s3 = dtm.getValueAt(i, 3).toString();
        String s4 = dtm.getValueAt(i, 4).toString();
        String s5 = dtm.getValueAt(i, 5).toString();
        String s6 = dtm.getValueAt(i, 6).toString();
        String s7 = dtm.getValueAt(i, 7).toString();
        String s8 = dtm.getValueAt(i, 8).toString();
        String s9 = dtm.getValueAt(i, 9).toString();

        jLabel27.setText(s);
        jTextField9.setText(s1);
        jTextField10.setText(s2);
        jTextField11.setText(s3);
        jTextField12.setText(s4);

        v.add(s5);
        jComboBox2.setModel(new DefaultComboBoxModel(v));

        jTextField13.setText(s6);

        v1.add(s7);
        jComboBox5.setModel(new DefaultComboBoxModel(v1));

        v2.add(s8);
        jComboBox6.setModel(new DefaultComboBoxModel(v2));

        jLabel34.setText(s9);
    }//GEN-LAST:event_jTable4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (jLabel27.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Select The Manuscript", "error", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                // TODO add your handling code here:
                //save approvel manu script
                String resdat = datechosser(jDateChooser1);
                String aprow;
                if (jCheckBox3.isSelected()) {
                    aprow = "Approve";
                } else {
                    aprow = "Reject";
                }

                ConnectionSet1.getInstance().setResult("update evaluation set recive_date='" + resdat + "',decision='" + aprow + "',reason='" + jTextArea1.getText() + "' where reseving_manuscript_idrm='" + jLabel27.getText() + "'");
                jLabel27.setText("");
                jTextField9.setText("");
                jTextField10.setText("");
                jTextField11.setText("");
                jTextField12.setText("");
                jTextField13.setText("");
                jLabel34.setText("");
                jTextArea1.setText("");
                jComboBox2.setSelectedIndex(0);
                jComboBox5.setSelectedIndex(0);
                jComboBox6.setSelectedIndex(0);
                jDateChooser1.setDate(null);
                buttonGroup1.clearSelection();
                jPanel10.setVisible(false);
                tableLoad();

            } catch (Exception ex) {
                Logger.getLogger(fullEvoluationProcess.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField14KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField14KeyReleased

        try {
            // TODO add your handling code here:
            // serch data
            new tablemodel1().fillTable("select idrm,fname,contact_no,email,manuscript_name,catergory,ms_type,send_to,sent_by,sent_date,recive_date,decision from evaluation e1 inner join reseving_manuscript r1 on e1.reseving_manuscript_idrm = r1.idrm inner join author a1 on r1.author_idauthor = a1.idauthor where decision='Approve' AND (fname like('" + jTextField14.getText() + "%%" + "') or manuscript_name like('" + jTextField14.getText() + "%%%" + "') or decision like('" + jTextField14.getText() + "%%%" + "'))", jTable5);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(fullEvoluationProcess.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(fullEvoluationProcess.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(fullEvoluationProcess.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jTextField14KeyReleased

    private void jTable5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable5MouseClicked
        // TODO add your handling code here:
        // set value from the all sent manu script table
        DefaultTableModel dtm = (DefaultTableModel) jTable5.getModel();
        int i = jTable5.getSelectedRow();
        Vector v = new Vector();
        Vector v1 = new Vector();
        Vector v2 = new Vector();

        String s = dtm.getValueAt(i, 0).toString();
        String s1 = dtm.getValueAt(i, 1).toString();
        String s2 = dtm.getValueAt(i, 2).toString();
        String s3 = dtm.getValueAt(i, 3).toString();
        String s4 = dtm.getValueAt(i, 4).toString();
        String s5 = dtm.getValueAt(i, 5).toString();
        String s6 = dtm.getValueAt(i, 6).toString();
        String s7 = dtm.getValueAt(i, 7).toString();
        String s8 = dtm.getValueAt(i, 8).toString();
        String s9 = dtm.getValueAt(i, 9).toString();
        String s10 = dtm.getValueAt(i, 10).toString();
        String s11 = dtm.getValueAt(i, 11).toString();

        jLabel27.setText(s);
        jTextField9.setText(s1);
        jTextField10.setText(s2);
        jTextField11.setText(s3);
        jTextField12.setText(s4);

        v.add(s5);
        jComboBox2.setModel(new DefaultComboBoxModel(v));

        jTextField13.setText(s6);

        v1.add(s7);
        jComboBox5.setModel(new DefaultComboBoxModel(v1));

        v2.add(s8);
        jComboBox6.setModel(new DefaultComboBoxModel(v2));

        jLabel34.setText(s9);

        Date d1 = new Date(s10);
        d1.getDate();
        jDateChooser1.setDate(d1);

        if (s11.equals("Approve")) {
            jCheckBox3.setSelected(true);
        } else {
            jCheckBox4.setSelected(true);
        }

    }//GEN-LAST:event_jTable5MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (jLabel27.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Select The Manuscript", "error", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                // TODO add your handling code here:
                //update approvel manu script
                String resdat = datechosser(jDateChooser1);
                String aprow;
                if (jCheckBox3.isSelected()) {
                    aprow = "Approve";
                } else {
                    aprow = "Reject";
                }

                ConnectionSet1.getInstance().setResult("update evaluation set recive_date='" + resdat + "',decision='" + aprow + "',reason='" + jTextArea1.getText() + "' where reseving_manuscript_idrm='" + jLabel27.getText() + "'");
                jLabel27.setText("");
                jTextField9.setText("");
                jTextField10.setText("");
                jTextField11.setText("");
                jTextField12.setText("");
                jTextField13.setText("");
                jLabel34.setText("");
                jTextArea1.setText("");
                jComboBox2.setSelectedIndex(0);
                jComboBox5.setSelectedIndex(0);
                jComboBox6.setSelectedIndex(0);
                jDateChooser1.setDate(null);
                buttonGroup1.clearSelection();
                jPanel10.setVisible(false);
                tableLoad();
            } catch (Exception ex) {
                Logger.getLogger(fullEvoluationProcess.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable6MouseClicked
        // TODO add your handling code here:
        // set value from the all sent manu script table
        DefaultTableModel dtm = (DefaultTableModel) jTable6.getModel();
        int i = jTable6.getSelectedRow();
        Vector v = new Vector();
        Vector v1 = new Vector();
        Vector v2 = new Vector();

        String s = dtm.getValueAt(i, 0).toString();
        String s1 = dtm.getValueAt(i, 1).toString();
        String s2 = dtm.getValueAt(i, 2).toString();
        String s3 = dtm.getValueAt(i, 3).toString();
        String s4 = dtm.getValueAt(i, 4).toString();
        String s5 = dtm.getValueAt(i, 5).toString();
        String s6 = dtm.getValueAt(i, 6).toString();
        String s7 = dtm.getValueAt(i, 7).toString();
        String s8 = dtm.getValueAt(i, 8).toString();
        String s9 = dtm.getValueAt(i, 9).toString();
        String s10 = dtm.getValueAt(i, 10).toString();
        String s11 = dtm.getValueAt(i, 11).toString();

        jLabel51.setText(s);
        jTextField17.setText(s1);
        jTextField18.setText(s2);
        jTextField19.setText(s3);
        jTextField20.setText(s4);

        v.add(s5);
        jComboBox7.setModel(new DefaultComboBoxModel(v));

        jTextField21.setText(s6);

        v1.add(s7);
        jComboBox8.setModel(new DefaultComboBoxModel(v1));

        v2.add(s8);
        jComboBox9.setModel(new DefaultComboBoxModel(v2));

        jLabel56.setText(s9);

        Date d1 = new Date(s10);
        d1.getDate();
        jDateChooser5.setDate(d1);

        jLabel60.setText(s11);
    }//GEN-LAST:event_jTable6MouseClicked

    private void jTable7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable7MouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable7.getModel();
        int i = jTable7.getSelectedRow();
        Vector v = new Vector();
        Vector v1 = new Vector();
        Vector v2 = new Vector();

        String s = dtm.getValueAt(i, 0).toString();
        String s1 = dtm.getValueAt(i, 1).toString();
        String s2 = dtm.getValueAt(i, 2).toString();
        String s3 = dtm.getValueAt(i, 3).toString();
        String s4 = dtm.getValueAt(i, 4).toString();
        String s5 = dtm.getValueAt(i, 5).toString();
        String s6 = dtm.getValueAt(i, 6).toString();
        String s7 = dtm.getValueAt(i, 7).toString();
        String s8 = dtm.getValueAt(i, 8).toString();
        String s9 = dtm.getValueAt(i, 9).toString();
        String s10 = dtm.getValueAt(i, 10).toString();
        String s11 = dtm.getValueAt(i, 11).toString();

        jLabel51.setText(s);
        jTextField17.setText(s1);
        jTextField18.setText(s2);
        jTextField19.setText(s3);
        jTextField20.setText(s4);

        v.add(s5);
        jComboBox7.setModel(new DefaultComboBoxModel(v));

        jTextField21.setText(s6);

        v1.add(s7);
        jComboBox8.setModel(new DefaultComboBoxModel(v1));

        v2.add(s8);
        jComboBox9.setModel(new DefaultComboBoxModel(v2));

        jLabel56.setText(s9);

        Date d1 = new Date(s10);
        d1.getDate();
        jDateChooser5.setDate(d1);

        jLabel60.setText(s11);
    }//GEN-LAST:event_jTable7MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        // clear all
        jLabel51.setText("");
        jTextField17.setText("");
        jTextField18.setText("");
        jTextField19.setText("");
        jTextField20.setText("");
        jTextField21.setText("");
        jLabel56.setText("");
        jLabel60.setText("");
        jComboBox7.setSelectedIndex(0);
        jComboBox8.setSelectedIndex(0);
        jComboBox9.setSelectedIndex(0);
        jDateChooser5.setDate(null);
        jCheckBox5.setSelected(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        //clear all
        jLabel27.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
        jTextField13.setText("");
        jLabel34.setText("");
        jComboBox2.setSelectedIndex(0);
        jComboBox5.setSelectedIndex(0);
        jComboBox6.setSelectedIndex(0);
        jDateChooser1.setDate(null);
        buttonGroup1.clearSelection();
        jPanel10.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // clear all
        jLabel3.setText("");
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField6.setText("");
        jComboBox1.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
        jComboBox4.setSelectedIndex(0);
        jDateChooser4.setDate(null);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (jLabel51.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Select The Manuscript", "error", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                // TODO add your handling code here:
                //update approvel manu script
                String resdat = datechosser(jDateChooser5);
                String aprow1 = null;
                if (jCheckBox5.isSelected()) {
                    aprow1 = "Approve";
                }

                ConnectionSet1.getInstance().setResult("update evaluation set recive_date='" + resdat + "',decision='" + aprow1 + "' where reseving_manuscript_idrm='" + jLabel51.getText() + "'");
                jLabel51.setText("");
                jTextField17.setText("");
                jTextField18.setText("");
                jTextField19.setText("");
                jTextField20.setText("");
                jTextField21.setText("");
                jLabel56.setText("");
                jLabel60.setText("");
                jComboBox7.setSelectedIndex(0);
                jComboBox8.setSelectedIndex(0);
                jComboBox9.setSelectedIndex(0);
                jDateChooser5.setDate(null);
                jCheckBox5.setSelected(false);
                tableLoad();
            } catch (Exception ex) {
                Logger.getLogger(fullEvoluationProcess.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField15KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField15KeyReleased
        try {
            // TODO add your handling code here:
            // serch data
            new tablemodel1().fillTable("select idrm,fname,contact_no,email,manuscript_name,catergory,ms_type,send_to,sent_by,sent_date,recive_date,decision from evaluation e1 inner join reseving_manuscript r1 on e1.reseving_manuscript_idrm = r1.idrm inner join author a1 on r1.author_idauthor = a1.idauthor where decision='Approve'"
                    + "AND (fname like('" + jTextField15.getText() + "%%" + "') or manuscript_name like('" + jTextField15.getText() + "%%%" + "') or decision like('" + jTextField15.getText() + "%%%" + "'))", jTable6);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(fullEvoluationProcess.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(fullEvoluationProcess.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(fullEvoluationProcess.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextField15KeyReleased

    private void jTextField16KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField16KeyReleased
        try {
            // TODO add your handling code here:
            //serch reject manuscript
            new tablemodel1().fillTable("select idrm,fname,contact_no,email,manuscript_name,catergory,ms_type,send_to,sent_by,sent_date,recive_date,decision from evaluation e1 inner join reseving_manuscript r1 on e1.reseving_manuscript_idrm = r1.idrm inner join author a1 on r1.author_idauthor = a1.idauthor"
                    + " where decision='Reject' AND (fname like('" + jTextField16.getText() + "%%" + "') or manuscript_name like('" + jTextField16.getText() + "%%%" + "') or decision like('" + jTextField16.getText() + "%%%" + "'))", jTable7);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(fullEvoluationProcess.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(fullEvoluationProcess.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(fullEvoluationProcess.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextField16KeyReleased

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        try {
            // TODO add your handling code here:
            //go home
            String uname = jLabel61.getText();
            String username = null;
            String desig = null;
            String typ = null;

            ResultSet rs = ConnectionSet1.getInstance().getResult("select * from user where username='" + uname + "'");
            if (rs.next()) {
                desig = rs.getString("designation");
                username = rs.getString("username");
                typ = rs.getString("user_type");

            }

            if (username.equals(uname) && typ.equals("Admin") && desig.equals("IT")) {
                System.out.println("3");
                new Menu("IT", "Admin", uname).setVisible(true);
                dispose();

            } else if (username.equals(uname) && typ.equals("Admin") && desig.equals("Publishing Manager")) {
                new Menu("Publishing Manager", "Admin", uname).setVisible(true);
                dispose();

            } else if (username.equals(uname) && typ.equals("User") && desig.equals("Assistant Publishing Manager")) {
                System.out.println("3");
                new Menu("Assistant Publishing Manager", "User", uname).setVisible(true);
                dispose();

            } else if (username.equals(uname) && typ.equals("Admin") && desig.equals("MD")) {
                System.out.println("3");
                new Menu("MD", "Admin", uname).setVisible(true);
                dispose();

            }
        } catch (Exception ex) {
            Logger.getLogger(costing.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fullEvoluationProcess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fullEvoluationProcess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fullEvoluationProcess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fullEvoluationProcess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fullEvoluationProcess().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private com.toedter.calendar.JDateChooser jDateChooser5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
